version: '3'

services:

  php-fpm:
    image: ${COMPOSE_PROJECT_NAME}/php-fpm
    env_file:
      - ${PWD}/docker/deploy/local/.env
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
    entrypoint: "/usr/local/bin/wait-for-it.sh mysql:3306 -- /usr/local/bin/dev-entrypoint.sh"
    volumes:
      - ${PWD}/app:/app

  nginx:
    image: ${COMPOSE_PROJECT_NAME}/nginx
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    volumes:
      - ${PWD}/app:/app
    ports:
      - 8081:80

  mysql:
    image: mysql:8
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - 33061:3306
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
#    volumes: #не использую
