controllers:
    resource: ../../src/Controller/
    type: annotation

controllers_api:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /v1

kernel:
    resource: ../../src/Kernel.php
    type: annotation
